import streamlit as st
import pandas as pd
import joblib
import numpy as np
import base64 # Import base64 for encoding SVG (though we're using URL for image)

# --- URL for Your GitHub Image ---
# This is the raw URL for your Heart.jpg on GitHub.
# Make sure 'Heart.jpg' is pushed to the root of your 'main' branch on GitHub.
GITHUB_HEART_IMAGE_URL = "https://raw.githubusercontent.com/Kennt96/capstone-stroke-predictor-app/main/Heart.jpg"

# --- Configuration for the Streamlit App ---
st.set_page_config(
    page_title="Heart Stroke Risk Predictor", # <--- CHANGED HERE
    page_icon=GITHUB_HEART_IMAGE_URL,
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- Load the Trained Model Pipeline ---
pipeline = None
try:
    pipeline = joblib.load('stroke_prediction_pipeline.pkl')
    st.success("Model pipeline loaded successfully!")
except FileNotFoundError:
    st.error("Error: Model file 'stroke_prediction_pipeline.pkl' not found.")
    st.info("Please ensure the model was saved correctly from your training script and is in the same directory as this app.")
    st.stop()
except Exception as e:
    st.error("An unexpected error occurred while loading the model pipeline.")
    st.error(f"**Detailed Loading Error:** {e}")
    st.info("This often indicates a scikit-learn version mismatch between where the model was saved and where it's being loaded. Ensure your `requirements.txt` specifies the exact scikit-learn version used during model training (e.g., `scikit-learn==1.6.1`).")
    st.stop()

if pipeline is None:
    st.stop()


# --- App Title and Description ---
st.title("Heart Stroke Risk Predictor") # <--- CHANGED HERE

# Display your GitHub image right below the title
st.image(GITHUB_HEART_IMAGE_URL, width=120)

st.markdown("""
    This application predicts the likelihood of a patient experiencing a stroke
    based on various health and demographic attributes.
    Please enter the patient's details in the sidebar.
""")

st.write("---")

# --- Sidebar for User Input ---
st.sidebar.header("Patient Data Input")

# Define input widgets for each feature
gender_options = ['Male', 'Female']
gender = st.sidebar.selectbox("Gender", gender_options)

age = st.sidebar.slider("Age (years)", min_value=0.0, max_value=82.0, value=45.0, step=0.1)

hypertension = st.sidebar.selectbox("Hypertension", [0, 1], format_func=lambda x: 'Yes' if x == 1 else 'No')

heart_disease = st.sidebar.selectbox("Heart Disease", [0, 1], format_func=lambda x: 'Yes' if x == 1 else 'No')

ever_married = st.sidebar.selectbox("Ever Married", ['Yes', 'No'])

work_type_options = ['Private', 'Self-employed', 'children', 'Govt_job', 'Never_worked']
work_type = st.sidebar.selectbox("Work Type", work_type_options)

residence_type_options = ['Urban', 'Rural']
Residence_type = st.sidebar.selectbox("Residence Type", residence_type_options)

avg_glucose_level = st.sidebar.number_input("Average Glucose Level", min_value=55.0, max_value=170.0, value=90.0, step=0.1)

bmi = st.sidebar.number_input("BMI (Body Mass Index)", min_value=10.0, max_value=50.0, value=25.0, step=0.1)

smoking_status_options = ['never smoked', 'Unknown', 'formerly smoked', 'smokes']
smoking_status = st.sidebar.selectbox("Smoking Status", smoking_status_options)

# --- Prediction Logic ---
input_data_df = pd.DataFrame([[
    gender, age, hypertension, heart_disease, ever_married,
    work_type, Residence_type, avg_glucose_level, bmi, smoking_status
]], columns=[
    'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
    'work_type', 'Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status'
])

# Button to trigger prediction
if st.sidebar.button("Predict Stroke Risk"):
    st.write("### Prediction Results:")
    try:
        prediction_proba = pipeline.predict_proba(input_data_df)[:, 1][0]
        prediction_class = pipeline.predict(input_data_df)[0]

        st.metric(label="Probability of Stroke", value=f"{prediction_proba * 100:.2f}%")

        if prediction_class == 1:
            st.error("⚠️ **HIGH RISK OF STROKE**")
            st.write("Based on the provided information, the model indicates a high likelihood of stroke.")
        else:
            st.success("✅ **LOW RISK OF STROKE**")
            st.write("Based on the provided information, the model indicates a low likelihood of stroke.")

        st.info("""
            **Disclaimer:** This prediction is generated by a machine learning model for informational purposes only.
            It should **not** be used as a substitute for professional medical advice, diagnosis, or treatment.
            Always consult with a qualified healthcare provider for any health concerns.
        """)
    except Exception as e:
        st.error(f"An error occurred during prediction. Please check your inputs. Error: {e}")

st.write("---")
st.markdown("Developed using Streamlit and Scikit-learn.")
